name: crs_flutter
description: A Flutter-based Courier Rating System application.

publish_to: 'none' # This is a private project.

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  # Local notifications
  flutter_local_notifications: ^18.0.1

  # Supabase
  supabase_flutter: ^2.5.3

  # Shared preferences
  shared_preferences: ^2.2.2

  # WebView for iframe
  webview_flutter: ^4.7.0

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
